### ISSUE TITLE
:shield: Security vulnerabilities

### ISSUE THREAD

**Issue by hitisec** [Cristy94/markdown-blog#5]
Hi,
Some potential security vulnerabilities has been identified in this repository.
Please Validate reports submitted on huntr and if are valid please mark them valid there.
The report links are the following:

https://huntr.dev/bounties/f7e6df41-9ebb-4859-845e-2d1485a135eb/
https://huntr.dev/bounties/28dc6c29-70bb-4814-8ed7-144bf07f3625/
https://huntr.dev/bounties/b479a2c9-9e45-438c-84fb-e3373edd07ae/

Regards

**Comment by Cristy94** [comment]
Hi,

Thanks for the report, I marked 2 out of the 3 as being valid.
The path traversal one seems to be blocked by mod_security by default, but it still has to be fixed.
