### ISSUE TITLE
function getFirstLines doesn’t seems to works

### ISSUE THREAD

**Issue by yazae** [Cristy94/markdown-blog#6]
Hi, as the title says, the function getFirstLines does not work in my test folder, with windows and PHP 8.1.

The blog post list render the full lenght of the markdown page : 

![image](https://github.com/Cristy94/markdown-blog/assets/88883564/0e20f4fb-e54b-43ca-9a17-0482fe15e3a2)

I see [here](https://stackoverflow.com/a/6666554) that PHP_EOL is behaving differently depending on if we are on a unix-based system or a windows one, maybe it’s where the problem is ?
Do you have any idea how to correct the problem ? I’m not a dev so it’s a bit hard for me, but I will try some things, it would be cool to be able to use your project !

**Comment by yazae** [comment]
Nevermind, the answer was very simple, replacing `PHP_EOL` with `"\n"` : 

```php
function getFirstLines($string, $count, $skip = 0) {
  $lines = array_slice(explode("\n", $string), $skip, $count);
  return implode("\n", $lines);
}
```

**Comment by Cristy94** [comment]
> Nevermind, the answer was very simple, replacing `PHP_EOL` with `"\n"` :
> 
> ```
> function getFirstLines($string, $count, $skip = 0) {
>   $lines = array_slice(explode("\n", $string), $skip, $count);
>   return implode("\n", $lines);
> }
> ```

Thanks for the comment!

This is strange though, isn't the whole point of `PHP_EOL` to be cross-platform and the main reason to use it over basic `\n`?

I assume the issue happens if you create the markdown files on one platform and upload them on a different one.
