### ISSUE TITLE
sorting and displaying the date

### ISSUE THREAD

**Issue by yazae** [Cristy94/markdown-blog#7]
Hi, the only functions who are lacking in my opinion are a way to choose the sorting of the blog post (it appears to be alphabetical (? - in the demo you doesn’t seem to have an alphabetical sorting ?), so if I name a .md post with the date, the posts will appear chronologically and not ante-chronologically, wich would be better. I also would like to display a date of the post.

How would you do the sorting ?
 
For displaying the date, in the RSS you seems to use `$post["create_date"]` but it may be a wrong date for the real posting date 🤔

**Comment by Cristy94** [comment]
There are two things here. I think some metadata would have to be added for each post. 

For the date to be correct, this could be manually set/updated (e.g. have some lines at the end of the markdown file that act as metadata).

Regarding sorting, you can change this function: https://github.com/Cristy94/markdown-blog/blob/f6e4593fa72d2d09ab448bf6962fb3da60274312/markdown-blog/postListRenderer.php#L4

You can sort the `$posts` array based on the conditions you want.

Maybe we could add some default sorting options and provide an option in the UI for them.

**Comment by Cristy94** [comment]
I have added default sorting by CREATED time (you can also change it to modified time): https://github.com/Cristy94/markdown-blog/commit/f1702531b504b38c69e37acd891b394206b39b84

Also now displaying creation date in posts list, can be also used as an example of how to display the date somewhere else: https://github.com/Cristy94/markdown-blog/commit/1079fc46b3aae950771bba92a43b2fba4ff3a017

**Comment by Cristy94** [comment]
Closing the issue for now, if you have more specific sorting questions, please open a new issue.

Thanks for the suggestion!

**Comment by yazae** [comment]
Thanks you very much for this update, I will try it right now :D
